#!/bin/bash

source wasm-env

export CFLAGS="-Ilib $CFLAGS"

CFILES="lib/progname.c\
  lib/closeout.c\
  lib/close-stream.c\
  lib/error.c\
  lib/quotearg.c\
  lib/exitfail.c\
  lib/c-strcasecmp.c\
  lib/xalloc-die.c\
  lib/xmalloc.c\
  lib/c-ctype.c\
  lib/xstrtoumax.c\
  src/version.c\
  lib/version-etc.c\
  lib/version-etc-fsf.c\
  lib/fadvise.c\
  lib/base64.c\
  lib/fclose.c\
  lib/malloc.c\
  lib/realloc.c\
  lib/open.c\
  lib/close.c\
  lib/fflush.c\
  lib/fpurge.c\
  lib/rpls.c\
  lib/fchdir.c\
  lib/filenamecat-lgpl.c\
  lib/basename-lgpl.c\
  lib/getprogname.c\
  lib/nl_langinfo.c\
  lib/xdectoumax.c\
  lib/binary-io.c\
  lib/xbinary-io.c\
  lib/localcharset.c\
  lib/fopen-safer.c\
  lib/dup-safer.c\
  lib/md5.c\
  lib/getline.c\
  lib/getdelim.c\
  lib/hard-locale.c\
  lib/xstrtoul.c\
  lib/argmatch.c\
  lib/freopen-safer.c\
  lib/posixver.c\
  lib/cloexec.c\
  lib/linebuffer.c\
  lib/memcasecmp.c\
  lib/xmemcoll.c\
  lib/memcoll.c\
  lib/dup2.c\
  "

$CC $CFLAGS $CFILES src/basenc.c -o base64.wasm $LDFLAGS -DBASE_TYPE=64
$CC $CFLAGS $CFILES src/md5sum.c -o md5sum.wasm $LDFLAGS -DHASH_ALGO_MD5
$CC $CFLAGS $CFILES src/uniq.c -o uniq.wasm $LDFLAGS
